#! /usr/bin/env python3
import sys
import re
from collections import Counter
from prettytable import PrettyTable

def parser(path):
  myregex = r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
  ip_list = re.findall(myregex,path)
  total = 0
  #print(ip_list)

  ipcount = Counter(ip_list)
  #print(ipcount)
  table = PrettyTable()
  table.field_names = ["ip", "count", "average"]


  total = len(ip_list)
  # print(total)

  for k, v in sorted(ipcount.items(), key=lambda x: x[1]):  
    average = (float(v)/ total ) * 100
    average = str(average)[0:6] + '%'
    ip = k
    count = str(v)
    average = str(average)
    table.add_row([ip, count, average])
  table.add_row(["Total", total, " "])

  print(table)

def main():
  path = sys.argv[1]
  with open(path) as f:
    log = f.read()
  parser(log)


if __name__ == '__main__':
  main()
            
