#! /usr/bin/env python3
import sys
import re
from collections import Counter

def parser(path):
  myregex = r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
  ip_list = re.findall(myregex,path)
  #return ip_list

  ipcount = Counter(ip_list)
  for k, v in ipcount.items():
    print(str(k) + " " + "Count" + "=>" + str(v))
  


def main():
  path = sys.argv[1]
  with open(path) as f:
    log = f.read()
  parser(log)


if __name__ == '__main__':
  main()
